package ua.konstantynov.hw29.enumerations;

public enum AlbumsNames {
    FLOW, COAST, TECHNIQUE, MEDIUM, TENSION, PARK, DISTINCT, CONTROL, LITERACY, ACQUISITION, INHIBITION,
    LOCATE, ROUTINE, ENVIRONMENT, BURIAL, CONTRARY, BASE, ALOOF, MEDIEVAL, CHEQUE, TEENAGER, PEACE, HEMISPHERE,
    TEMPT, CHAMPAGNE, HEEL, EXECUTRIX, MOLE, SLICE, WRITE, CONTENT, TERRIFY, ESTATE, BACK, INCREDIBLE, INFECTION,
    ROOF, ORGAN, SPIT, HABIT, PICTURE, REALISM, TON, REFERENCE, SNOW, AMBIGUOUS, CHARACTERISTIC, ESSAY, WEAKNESS
}
