package ua.konstantynov.hw29.enumerations;

public enum ArtistsNames {
    JOEL_POTTER, LETICIA_HUME, BESSIE_FOREMAN, JOHANNA_COATES, KODY_LOVE, HANAN_CHAMBERLAIN,
    VIKTOR_NEALE, DEVONTE_GAMBLE, COBY_WILEY, KIRSTIE_BOOKER, ZAYN_KIRK, JONTY_KHAN, MILANA_MCCANN,
    ROSE_SHERIDAN, ELSIE_DALY, ZIGGY_KAY, ELIANA_CAIRNS, VIVIENNE_WEEKS, SAMIRAH_THOMPSON, ISHAN_RODGERS,
    HAREEM_GRIMES, BUSTER_CROSSLEY, MILDRED_CORRIGAN, IANIS_MORLEY, ANYA_FERREIRA, CONOR_MEZA, DEBORAH_BARKER,
    CELIA_BARRETT, HUSSEIN_DALBY, JAIDAN_SANFORD, NIMRAH_WOLFE, HUMERA_PARKES, GERALDINE_MCCALLUM,
    ABDULLAHI_WARE, ROSE_MOHAMMED, ALASDAIR_PARKER, HOPE_FINCH, EVIE_PHAN, ABBAS_ROWE, INDIA_DOTSON, DANIKA_PLANT,
    AMANDA_HIBBERT, UMAIMA_SOLIS, AEDAN_MARQUEZ, DIGBY_TRUONG, SYEDA_CALLAGHAN, LOWRI_HARMON, NOAH_PARK, KAVITA_HORNE
}
