package ua.konstantynov.hw29.enumerations;

public enum Genders {
    AGENDER, ANDROGYNE, ANDROGYNOUS, ATTACK_HELICOPTER, BIGENDER, CISGENDER, CISGENDER_FEMALE, CISGENDER_MALE,
    CISGENDER_MAN, CISGENDER_WOMAN, FEMALE_TO_MALE, FTM, GENDER_FLUID, GENDER_NONCONFORMING, GENDER_QUESTIONING,
    GENDER_VARIANT, GENDERQUEER, INTERSEX, MALE_TO_FEMALE, MTF, NEITHER, NEUTROIS, NON_BINARY, OTHER, PANGENDER,
    TRANS, TRANS_FEMALE, TRANS_MALE, TRANS_MAN, TRANS_PERSON, TRANS_WOMAN, TRANSFEMININE, TRANSGENDER,
    TRANSGENDER_FEMALE, TRANSGENDER_MALE, TRANSGENDER_MAN, TRANSGENDER_PERSON, TRANSGENDER_WOMAN, TRANSMASCULINE,
    TRANSSEXUAL, TRANSSEXUAL_FEMALE, TRANSSEXUAL_MALE, TRANSSEXUAL_MAN, TRANSSEXUAL_PERSON, TRANSSEXUAL_WOMAN,
    TWO_SPIRIT
}
